[package]
name = "rs_poc_wrapped"
version = "0.1.0"
edition = "2021"
description = "A proof of concept for a type that tries to be a translucent wrapper"
publish = false

[dependencies]
serde = { version = "1", features = [ "derive" ]}
serde_json = "1"
